### ISSUE TITLE
Oldlace Ruddy Africanaugurbuzzard

### ISSUE THREAD

**Issue by ValentineRain** [ScoreShots/templatemigration#182]
![](https://scoreshotstemplates.s3.amazonaws.com/339.jpg)

# 

* Legacy name: Preview 6
* Legacy File: https://scoreshotstemplates.s3.amazonaws.com/339.json
* Legacy Category: DevelopmentTest

* Potentially Problematic Elements: 
We don't really need this in the development category anymore. Adam was probably testing something. We can retire it.

* Long-term potential merge candidates

**Comment by adavila17** [comment]
this is in football category anyway
