### ISSUE TITLE
Peru Stupendous Foxterrier

### ISSUE THREAD

**Issue by ValentineRain** [ScoreShots/templatemigration#254]
![](https://scoreshotstemplates.s3.amazonaws.com/415.jpg)
This template does not exist and was probably made in err. 

# 

* Legacy name: SocialShot 1
* Legacy File: https://scoreshotstemplates.s3.amazonaws.com/415.json
* Legacy Category: Tennis

* Potentially Problematic Elements: 

* Long-term potential merge candidates

**Comment by adavila17** [comment]
no preview

**Comment by adavila17** [comment]
omahgeeerd no image.

**Comment by adavila17** [comment]
no preview
