### ISSUE TITLE
Instructive Moral Sakimonkey

### ISSUE THREAD

**Issue by ValentineRain** [ScoreShots/templatemigration#270]
![](https://scoreshotstemplates.s3.amazonaws.com/432.jpg)

# 

* Legacy name: CardShot 1
* Legacy File: https://scoreshotstemplates.s3.amazonaws.com/432.json
* Legacy Category: DevelopmentTest

* Potentially Problematic Elements: 

* Long-term potential merge candidates 
We were probably testing #269. This copy is no longer needed.

**Comment by Aubron** [comment]
Closing as a copy of a real template.
