### ISSUE TITLE
Mediumvioletred Runny Copepod

### ISSUE THREAD

**Issue by ValentineRain** [ScoreShots/templatemigration#286]
![](https://scoreshotstemplates.s3.amazonaws.com/448.jpg)

# 

* Legacy name: NewPartnerShot
* Legacy File: https://scoreshotstemplates.s3.amazonaws.com/448.json
* Legacy Category: Internal Use

* Potentially Problematic Elements: 
No longer useful.

* Long-term potential merge candidates 

### Template Types Recommendation:
* Internal

**Comment by Aubron** [comment]
Want to make a motion version of this to compete with BoxOut.
