### ISSUE TITLE
Deleted Useless Warthog

### ISSUE THREAD

**Issue by ValentineRain** [ScoreShots/templatemigration#307]
![](https://scoreshotstemplates.s3.amazonaws.com/471.jpg)

# 

* Legacy name: StartingShot 3
* Legacy File: https://scoreshotstemplates.s3.amazonaws.com/471.json
* Legacy Category: DevelopmentTest

* Potentially Problematic Elements: 
It's a development template, we don't need this copy anymore.

**Comment by Aubron** [comment]
Closing this as it is a development copy of another template.
