### ISSUE TITLE
Immolated Somewhatracey Lich

### ISSUE THREAD

**Issue by ValentineRain** [ScoreShots/templatemigration#363]
![](https://scoreshotstemplates.s3.amazonaws.com/532.jpg)

This template is inactive.

# 

* Legacy name: FinalShot 4
* Legacy File: https://scoreshotstemplates.s3.amazonaws.com/532.json
* Legacy Category: Volleyball

* Potentially Problematic Elements: 

* Long-term potential merge candidates 
Retire.

**Comment by adavila17** [comment]
no image attached.
