### ISSUE TITLE
Chivalrous Plant Animal

### ISSUE THREAD

**Issue by ValentineRain** [ScoreShots/templatemigration#386]
![](https://scoreshotstemplates.s3.amazonaws.com/555.jpg)
This is a development template.

# 

* Legacy name: AubronTest
* Legacy File: https://scoreshotstemplates.s3.amazonaws.com/555.json
* Legacy Category: WVU Mountaineers

* Potentially Problematic Elements: 
No longer needed. Retire.

* Long-term potential merge candidates

**Comment by adavila17** [comment]
no image but if WVU then yeah retire.
