### ISSUE TITLE
 Odd Statuesque Partridgeinapeartree

### ISSUE THREAD

**Issue by ValentineRain** [ScoreShots/templatemigration#401]
![](https://scoreshotstemplates.s3.amazonaws.com/571.jpg)

# 

* Legacy name: "startingshot 4"
* Legacy File: https://scoreshotstemplates.s3.amazonaws.com/571.json
* Legacy Category: DevelopmentTest

* Potentially Problematic Elements: 
Internal template which is no longer needed.

* Long-term potential merge candidates

**Comment by adavila17** [comment]
no image attached.
