### ISSUE TITLE
 Stimulating Rustic Ptarmigan

### ISSUE THREAD

**Issue by ValentineRain** [ScoreShots/templatemigration#402]
![](https://scoreshotstemplates.s3.amazonaws.com/572jpg)

# 

* Legacy name: StartingShot 2
* Legacy File: https://scoreshotstemplates.s3.amazonaws.com/572.json
* Legacy Category: DevelopmentTest

* Potentially Problematic Elements: 
Development template, no longer needed.

* Long-term potential merge candidates

**Comment by adavila17** [comment]
no image attached.
