### ISSUE TITLE
Maniacal Whimsical Riograndeescuerzo

### ISSUE THREAD

**Issue by ValentineRain** [ScoreShots/templatemigration#403]
![](https://scoreshotstemplates.s3.amazonaws.com/573.jpg)

# 

* Legacy name: PreviewShot 1
* Legacy File: https://scoreshotstemplates.s3.amazonaws.com/573.json
* Legacy Category: DevelopmentTest

* Potentially Problematic Elements: 
Development template, no longer needed.

* Long-term potential merge candidates

**Comment by adavila17** [comment]
no image attached.
