### ISSUE TITLE
Abiding Unsightly Doggo

### ISSUE THREAD

**Issue by ValentineRain** [ScoreShots/templatemigration#406]
![](https://scoreshotstemplates.s3.amazonaws.com/576.jpg)

# 

* Legacy name: StartingShot 8
* Legacy File: https://scoreshotstemplates.s3.amazonaws.com/576.json
* Legacy Category: DevelopmentTest

* Potentially Problematic Elements: 
Development Template. Retire.

* Long-term potential merge candidates

**Comment by adavila17** [comment]
no image attached.
