### ISSUE TITLE
Waggish Illegal Mudpuppy

### ISSUE THREAD

**Issue by ValentineRain** [ScoreShots/templatemigration#407]
![](https://scoreshotstemplates.s3.amazonaws.com/577.jpg)

# 

* Legacy name: "Pooptato"
* Legacy File: https://scoreshotstemplates.s3.amazonaws.com/577.json
* Legacy Category: DevelopmentTest

* Potentially Problematic Elements: 
Development template. Retire.

* Long-term potential merge candidates

**Comment by adavila17** [comment]
no image of template attached.
