### ISSUE TITLE
Closed Dapper Ziplockbag

### ISSUE THREAD

**Issue by ValentineRain** [ScoreShots/templatemigration#458]
![](https://scoreshotstemplates.s3.amazonaws.com/629.jpg)

# 

* Legacy name: ScheduleShot 6
* Legacy File: https://scoreshotstemplates.s3.amazonaws.com/629.json
* Legacy Category: Media Relations

* Potentially Problematic Elements: 

* Long-term potential merge candidates 
This is an unused variant of #458

**Comment by adavila17** [comment]
no preview image.
