### ISSUE TITLE
Parsimonious Breezy Oneeyedpigeon

### ISSUE THREAD

**Issue by ValentineRain** [ScoreShots/templatemigration#462]
![](https://scoreshotstemplates.s3.amazonaws.com/634.jpg)

# 

* Legacy name: SocialShot 4
* Legacy File: https://scoreshotstemplates.s3.amazonaws.com/634.json
* Legacy Category: Media Relations

* Potentially Problematic Elements: 
This template never finished development. There's not much on it. Retire.

* Long-term potential merge candidates

**Comment by adavila17** [comment]
no preview image of template
