### ISSUE TITLE
festive long long long long long long looooooooong longcat

### ISSUE THREAD

**Issue by ValentineRain** [ScoreShots/templatemigration#463]
![](https://scoreshotstemplates.s3.amazonaws.com/635.jpg)

# 

* Legacy name: SocialShot 2
* Legacy File: https://scoreshotstemplates.s3.amazonaws.com/635.json
* Legacy Category: Media Relations

* Potentially Problematic Elements: 
Template never completed development. Retire.

* Long-term potential merge candidates

**Comment by adavila17** [comment]
no preview image of template.
