### ISSUE TITLE
Long-term Languid Lungfish

### ISSUE THREAD

**Issue by ValentineRain** [ScoreShots/templatemigration#484]
![](https://scoreshotstemplates.s3.amazonaws.com/657.jpg)

# 

* Legacy name: ScheduleShot 9
* Legacy File: https://scoreshotstemplates.s3.amazonaws.com/657.json
* Legacy Category: DevelopmentTest

* Potentially Problematic Elements: 

* Long-term potential merge candidates 
Retire, development template.

**Comment by adavila17** [comment]
no preview image to see template.
