### ISSUE TITLE
Smooth Goofy Civet

### ISSUE THREAD

**Issue by ValentineRain** [ScoreShots/templatemigration#487]
![](https://scoreshotstemplates.s3.amazonaws.com/660.jpg)

# 

* Legacy name: "PlayerShot#Windians"
* Legacy File: https://scoreshotstemplates.s3.amazonaws.com/660.json
* Legacy Category: DevelopmentTest

* Potentially Problematic Elements: 

* Long-term potential merge candidates 
No longer needed, development template. Retire.

**Comment by adavila17** [comment]
i haz no preview image.... merp.
